name: snap2stamps
channels:
  - r
  - defaults
  - eumetsat
  - https://conda.anaconda.org/conda-forge
  - conda-forge
  - mdelgadoblasco
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - fftw3
  - geos=3.8.0
  - intel-openmp=2023.1.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - ncurses=6.4
  - numpy=1.25.0
  - numpy-base=1.25.0
  - openssl=3.0.9
  - pip=23.1.2
  - python=3.11.3
  - readline=8.2
  - setuptools=67.8.0
  - shapely=2.0.1
  - s1tbx=9.0.2
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
    - argparse==1.4.0
    - asf-search==6.5.0
    - attrs==23.1.0
    - certifi==2023.5.7
    - charset-normalizer==3.1.0
    - cligj==0.7.2
    - configparser==5.3.0
    - dateparser==1.1.8
    - fiona==1.9.4.post1
    - geopandas==0.13.2
    - idna==3.4
    - importlib-metadata==6.7.0
    - packaging==23.1
    - pandas==2.0.2
    - pyproj==3.6.0
    - python-dateutil==2.8.2
    - pytz==2023.3
    - regex==2023.6.3
    - remotezip==0.12.1
    - requests==2.31.0
    - six==1.16.0
    - tabulate==0.9.0
    - tenacity==8.2.2
    - tzdata==2023.3
    - tzlocal==5.0.1
    - urllib3==2.0.3
    - zipp==3.15.0
